# Generated by Django 4.2.10 on 2024-08-28 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
