# Generated by Django 4.2.10 on 2024-08-28 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_author_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
